# Generated by Django 4.2.13 on 2024-07-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categpry',
            new_name='Category',
        ),
    ]
