# Generated by Django 4.2.13 on 2024-07-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='messege',
            new_name='message',
        ),
    ]
